version: 2.1

jobs:
  build_and_release:
    macos:
      xcode: 15.4.0
    steps:
      - checkout
    
      - run:
          name: SET BUILD TAG BASED ON BRANCH
          command: |
            plist_path="./distribution/ExportOptions.plist"
            branch_name=$(echo ${CIRCLE_BRANCH} | sed 's/\//-/g')
            
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              tag="Master"
            elif [ "$CIRCLE_BRANCH" == "staging" ]; then
              tag="Staging"
            else
              tag="Feature-${branch_name}"
            fi
            
            # Check if uploadMetadata exists, if not add it
            if /usr/libexec/PlistBuddy -c "Print :uploadMetadata" $plist_path; then
              /usr/libexec/PlistBuddy -c "Set :uploadMetadata '${tag} Build'" $plist_path
            else
              /usr/libexec/PlistBuddy -c "Add :uploadMetadata string '${tag} Build'" $plist_path
            fi

workflows:
  build_and_release:
    jobs:
      - build_and_release