version: 2.1

jobs:
  build_and_release:
    macos:
      xcode: 15.4.0
    steps:
      - checkout

      - run:
          name: INSTALL Github CLI and Python Dependancies
          command: |
            brew install ghr
            
      - run:
          name: SET BUILD TAG BASED ON BRANCH
          command: |
            ./create_tag.sh
workflows:
  build_and_release:
    jobs:
      - build_and_release
