version: 2.1

jobs:
  build_and_release:
    macos:
      xcode: 15.4.0
    steps:
      - checkout

      - run:
          name: SET BUILD TAG BASED ON BRANCH
          command: |
            node hello.js
workflows:
  build_and_release:
    jobs:
      - build_and_release
