version: 2.1

jobs:
  build_and_release:
    macos:
      xcode: 15.4.0
    steps:
      - checkout

      - run:
          name: SET BUILD TAG BASED ON BRANCH
          command: |
            plist_path="./distribution/ExportOptions.plist"
            branch_name=$(echo ${CIRCLE_BRANCH} | sed 's/\//-/g')
            
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              tag="Master"
            elif [ "$CIRCLE_BRANCH" == "staging" ]; then
              tag="Staging"
            else
              tag="Feature-${branch_name}"
            fi
            echo '${tag} Build'
            /usr/libexec/PlistBuddy -c "Set :uploadMetadata '${tag} Build'" $plist_path

      - run:
          name: PRINT LATEST plist CONTENTS
          command: |
            plist_path="./distribution/ExportOptions.plist"
            echo "Current contents of $plist_path:"
            /usr/libexec/PlistBuddy -c "Print" $plist_path

workflows:
  build_and_release:
    jobs:
      - build_and_release
