version: 2.1

jobs:
  build_and_test_branch:
    steps:
      - checkout
      - run:
          name: DETERMINE BUILD TAG BASED ON BRANCH
          command: |
            # Get the branch name
            branch_name=$(echo ${CIRCLE_BRANCH} | sed 's/\//-/g')  # Replace slashes with dashes
            
            # Conditional logic to set the appropriate tag
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              tag="Master"
            elif [ "$CIRCLE_BRANCH" == "staging" ]; then
              tag="Staging"
            else
              tag="Feature-${branch_name}"
            fi

            # Print the determined tag
            echo "Build Tag: ${tag}"
      
      # Optional: Store artifacts if you want to inspect them later
      - store_artifacts:
          path: build
          destination: build_artifacts

workflows:
  build_and_test_branch:
    jobs:
      - build_and_test_branch:
          filters:
            branches:
              only:
                - master
                - staging
                - feature/test-branch  # You can replace this with any other branch you want to test
